### ISSUE TITLE
NSFS: Noobaa uninstall gets stuck at namespace deletion step

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-operator#632]
### Environment info
- NooBaa Version: master-20210428-nsfs
- Platform: OCP 4.6.16

### Actual behavior
1. Noobaa uninstall via step "noobaa uninstall --cleanup=true" gets stuck at namespace deletion step

### Expected behavior
1. Noobaa uninstall should NOT get stuck at any stage

### Steps to reproduce
1. Install Noobaa code via binary from dockerhub page. 
2. Attempt uninstall using step "noobaa uninstall --cleanup=true"
3. Uninstall is stuck and had to force clean. 

### More information - Screenshots / Logs / Other output

I don't have the logs currently available with me but this is seen multiple times. If you need help in recreating, would provide the logs.

**Comment by nimrod-becker** [comment]
@akmithal moved to operator

**Comment by rohantmp** [comment]
Came here to log an issue about NooBaa CR delete getting stuck. I'm guessing the CLI uninstall also does this.
The delete gets stuck, but restarting the operator allows it to proceed. I'm guessed it was because of the predicate:
```
	err = c.Watch(&source.Kind{Type: &nbv1.NooBaa{}}, &handler.EnqueueRequestForObject{},
		noobaaPredicate, &logEventsPredicate)
	if err != nil {
		return err
	}
```
but, I tested with a finalizer I manually added and doing a delete(adding a deletion timestamp does change the generation, so theoretically `noobaaPredicate` should pass. So there goes my theory.

**Comment by guymguym** [comment]
@rohantmp is that `oc get lvset` output related?
What we would need to check once reproduced is which resources are still stuck in the namespace - see https://stackoverflow.com/a/53016918/2702164 and maybe `kubectl describe namespace NNN` and `kubectl get events -n NNN --sort-by=.lastTimestamp`
Finalizers are usually the blaim, but stuck containers might also occur due to some lower level problem (like unresponsive mounts, etc).

**Comment by rohantmp** [comment]
My guess was that the reconcile is not being triggered on delete because of the predicate(because restarting the operator pod let the delete proceed), so the lvset output is an experiment to see if the finalizer changes the generation and passes the watch predicate.

**Comment by romayalon** [comment]
Hey @akmithal,
I tried to reproduce it multiple times on minikube, without success.
Do you still experience this issue in the latest version? if so, can you keep the cluster when it gets stuck and run Guy's suggestions?
Thank you

**Comment by nimrod-becker** [comment]
@akmithal any news on this?

**Comment by akmithal** [comment]
This is working on latest builds, hence closing it. Thanks.
